### ISSUE TITLE
Add output file of manually input answers, add ability to process a file containing those answers

### ISSUE THREAD

**Issue by moosecanswim** [galaho/pathogen#14]
If we use this tool to build out files from templates it would be helpful 1) to output a file containing the manually input answers
2) add ability to process input file 

These changes would be helpful if the template changes then we could continue to use the same input values to generate updated files.

Example usage: generate 1.1 config files for proxy and listener.  in 1.2 the some fields that were defined in proxy file are moved to listener file.  If we have the answers file used to generate the 1.1 configs then we can just apply that to the 1.2 templates.  

This is not so bad when we have 10 services but if an organization had 1000 services the update process would be a real time sink

**Comment by chrisbsmith** [comment]
This may be completed by simply adding a file to the folder that writes out the input values. Since Pathogen runs through all of the files in a folder, it will just spit out the file with the inputed values.

**Comment by joshua-rutherford** [comment]
@chrisbsmith, I'm not sure that solves the ask from @moosecanswim though.  What you'd need is the ability still to read in that file when you execute.  That should be simple enough.

However, in practice I think you'll run into troubles attempting to do what you propose.  Templates are extremely useful for quickly generating the files but after generation they can change for any number of reasons and simply regenerating with the new templates would be problematic as you would not capture the changes that were made.  If you try to make your templates so dynamic that you can handle all of these things I think you'll drive yourself crazy.

**Comment by joshua-rutherford** [comment]
Looking at another issue, I just realizes we might as well allow for file based variable resolution and it's fairly straight forward.  I propose adding a flag to the `generate` command that allows for the specification of a resolver other than the IO resolver.

```
pathogen generate [-i|--input FILE] SOURCE DESTINATION
```

When not set we'd resort to the current interactive resolver but when provided we'd use a file based resolver.  This is really trivial and sets the stage for implementing something like the above.

**Comment by chrisbsmith** [comment]
@joshua-rutherford you can close this issue.
